### ISSUE TITLE
Library link is broken

### ISSUE THREAD

**Issue by TheRouce** [leapmotion-examples/VRIntro#14]
The link to the libraries in the readme is broken, and of course when I compile without them it throws up all kinds of errors 

```
CMake Error at source/CMakeLists.txt:4 (find_package):
  By not providing "FindComponents.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Components", but CMake did not find one.

  Could not find a package configuration file provided by "Components" with
  any of the following names:

    ComponentsConfig.cmake
    components-config.cmake

  Add the installation prefix of "Components" to CMAKE_PREFIX_PATH or set
  "Components_DIR" to a directory containing one of the above files.  If
  "Components" provides a separate development package or SDK, be sure it has
  been installed.
```

I figure hhe won't actually respond because of how old this is, but just in case I wanted to see if I could get a new link or even just a list of the things I need to find on my own and download.

**Comment by hhe** [comment]
Hi @Petr05,

Sadly the Box link expires after a few years. I don't have the ability to restore it but you can try this mirror: https://drive.google.com/open?id=1T90kqHqk6Mjs2wZPtDilDOHfGQ-De8FC

You may run into more issues unless your entire setup (LeapSDK, Oculus, MSVC, Cmake) is from the 2015 era. Good luck!

Jimmy

**Comment by TheRouce** [comment]
Thank you so much for the quick response, I figured I was gonna run into more problems, but at least I can get past this one!
